### PR TITLE
Windows fixes and stuff

### PR DESCRIPTION
**Pull request by Lopi-py**
fix(windows): use path.sanitize to handle correctly windows paths with lspconfig
fix(config): config.values.float -> config.values.local_settings_root_markers
fix(core): changed typo err -> err_ in nlspsettings.lua when checking local config errors
feat(log): use nvim-notify if available or vim.notify
feat(selection): use vim.ui.select to select a server
feat(path): use lspconfig.util.path to handle path stuff like is_file, is_dir, etc
feat(array): use next() to check if an array is empty
fix(local-buf-config): `vim.lsp.get_client_by_id(server.client_id)` was used where server is getted from `get_server_name()` so doesn't make sense(because a string does not have the `client_id` property)

[example](https://gyazo.com/d9fc0af97f1278a9b5523c38d65709c5) of `vim.ui.select` with [dressing](https://github.com/stevearc/dressing.nvim)(without dressing looks like before)
[example](https://gyazo.com/0727c87ba66b2a6f8cb17651ade35846) of [nvim-notify](https://github.com/rcarriga/nvim-notify)

### CODE REVIEW

**Comment by tamago324** [comment]
Thank you for the PR.
Sorry for the late reply.

I would like to make the nvim-notify thing optional.
So, I would like to set the default value in `config.lua` as follows.

```lua
local defaults_values = {
  ...
  nvim_notify = {
    enable = false,
    timeout = 5000,
  }
}
```

I think it will also change the `command.lua`.

```lua
local log = function(message, level)
  local title = 'NLsp Settings'

  local config_notify = config.get('nvim_notify')
  if notify and config_notify and config_notify.enable then
    notify(message, level, {
      title = title,
      timeout = config_notify.timeout,
    })
  else
    vim.notify(('[%s] '):format(title) .. message, level)
  end
end
```


Please also change the [README](https://github.com/Lopi-py/nlsp-settings.nvim/blob/45dced09b1b161a6dd18c9c59be86eedae915387/README.md?plain=1#L21-L29).

```vim
## Installation

Plug 'neovim/nvim-lspconfig'
Plug 'tamago324/nlsp-settings.nvim'

" Recommend
Plug 'williamboman/nvim-lsp-installer'

" Optional
Plug 'rcarriga/nvim-notify'
```


Also, please add it to the help file.

**Comment by Lopi-py** [comment]
> ```lua
> local defaults_values = {
>   ...
>   nvim_notify = {
>     enable = false,
>     timeout = 5000,
>   }
> }
> ```

I think it should be enabled by default

**Comment by tamago324** [comment]
I'm going to merge it as is, and I'm sorry if it offends you.

Thank you for your contribution.

**Comment by Lopi-py** [comment]
> I'm sorry if it offends you.

dw, doesn't matter

**Pull request merged**
