### PR TITLE
Rename local_settings_root_makers to local_settings_root_markers_fallback and use lspconfig.<server_name>.get_root_dir instead

### PR DESCRIPTION
**Pull request by shurizzle**
I was working on a rust project and I noticed that root for the package was wrong because of "manual" root deduction.
Instead of using root markers I'm using the builtin root finder in lspconfig that you are already using and root markers as a fallback, so I renamed variable configuration to better represent it.

Nice work btw 😃

### CODE REVIEW

**Comment by tamago324** [comment]
Thank you for your contribution.
Could you also fix doc/nlspsettings.txt?

**Comment by shurizzle** [comment]
I'm thinking about insert .nlsp-settings as default in local_settigns_root_markers_fallback so you can use it as a marker if you had to manually configure the project. What do you think about it?

**Comment by tamago324** [comment]
I think its a good idea!
Let's add .nlsp-settings.

**Comment by tamago324** [comment]
Thank you!

**Pull request merged**
