### PR TITLE
nvim-lsp-installer integration

### PR DESCRIPTION
**Pull request by Lopi-py**
Get only installed servers to complete
image

### CODE REVIEW

**Comment by tamago324** [comment]
Thanks for the PR.
However, I don't want to make it mandatory, because I can install LSP server without using nvim-lsp-installer.
Therefore, I can't incorporate this PR as is.

Do you have any other ideas?

**Comment by Lopi-py** [comment]
I can check if `require'nvim-lsp-installer'` throws an error to check if is installed

**Comment by registerGen** [comment]
> Get only installed servers to complete

> However, I don't want to make it mandatory, because I can install LSP server without using nvim-lsp-installer.

Maybe this is better.

```lua
for lsp, _ in pairs(require('lspconfig.configs')) do
  print(vim.inspect(lsp))
end
```

**Comment by registerGen** [comment]
We can use `nvim-lspconfig` to detect which LSP servers we've installed.

**Comment by tamago324** [comment]
@registerGen 
`require('lspconfig.configs')` seems like a very good idea!

**Comment by tamago324** [comment]
But I'm not sure.
I think there can be any number of complementary candidates.

The reason is that you can enter the server name of the configuration file you want to open yourself.
That's why I don't feel good about this PR.

**Comment by Lopi-py** [comment]
Yeah, use `lspconfig.configs` is the better way, but if you like I can make it optional

**Pull request closed without merging**
