### PR TITLE
Local settings

### LINKED ISSUE #4: Load local settings
I want to be able to read the local configuration for each repository (root_dir).
The idea came from a [comment on reddit](https://www.reddit.com/r/neovim/comments/mhy2p8/nlspsettings_a_plugin_for_setting_neovim_lsp_with/gt8z3ct?utm_source=share&utm_medium=web2x&context=3).

It would be nice to be able to read settings files such as `.nlsp-settings/sumneko_lua.json`.

### PR DESCRIPTION
**Pull request by tamago324**
close #4.

### CODE REVIEW

**Comment by tamago324** [comment]
マージするなら、これも実装する

https://github.com/mattn/vim-lsp-settings/pull/441

**Comment by meijieru** [comment]
Will this PR be merged soon?

**Comment by cweagans** [comment]
Is there anything blocking this that I can help with?

**Comment by tamago324** [comment]
@cweagans I'm sorry. It's due to my motivation.
I am not motivated because I have to rewrite a lot of code...

**Comment by cweagans** [comment]
Don't be sorry! That's totally normal. Can I help somehow? Do you just need this redone against HEAD?

**Comment by tamago324** [comment]
Yes. That's right.
I would also like to apply the https://github.com/mattn/vim-lsp-settings/pull/441 changes.
If possible, I would like you to do it for me, is that okay?

**Comment by cweagans** [comment]
Ah, looks like you beat me to it. Apologies for the delay. I was busy with family the past couple of days. Do you still need https://github.com/mattn/vim-lsp-settings/pull/441 done?

**Comment by tamago324** [comment]
No, no, it's not your fault. It's Christmas and it's good to spend time with family :christmas_tree: 
Your comment has motivated me. Thank you.

Since dangerous settings such as `cmd` are not configurable in nlsp-settings.nvim, we decided that it was not necessary to include mattn/vim-lsp-settings#441.
If you have any problems, please let me know.

**Comment by cweagans** [comment]
Sounds great! Thanks for getting this across the finish line. This will be very helpful to me!!

**Pull request closed without merging**
